version: '2'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_USER=demo"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=demo"
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus:v2.29.1
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.5.10
    environment:
      GF_SECURITY_ADMIN_PASSWORD: proton
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./monitoring/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
