{
 "title": "Ktor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate KTOR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ktor_http_server_requests_seconds_count{framework=\"ktor\"}[1m]) )"
    }
   ]
  },
  {
   "title": "Request Rate Spring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{framework=\"spring\"}[1m]) )"
    }
   ]
  },
  {
   "title": "Response Time KTOR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds_sum{ framework=\"ktor\" }[1m]) / rate(ktor_http_server_requests_seconds_count{ framework=\"ktor\" }[1m])",
     "legendFormat": " {{ status }}"
    }
   ]
  },
  {
   "title": "Response Time Spring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{ framework=\"spring\", uri=\"/\" }[1m]) / rate(http_server_requests_seconds_count{ framework=\"spring\", uri=\"/\" }[1m])",
     "legendFormat": " {{ status }}"
    }
   ]
  },
  {
   "title": "Memory Usage KTOR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{framework=\"ktor\"}) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Memory Usage Spring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{framework=\"spring\"}) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Threads KTOR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{framework=\"ktor\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Threads Spring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{framework=\"spring\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Active Http Requests Ktor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_active"
    }
   ]
  },
  {
   "title": "Active Http Requests Spring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions"
    }
   ]
  }
 ]
}